### ISSUE TITLE
error on cmake, latest build

### ISSUE THREAD

**Issue by zfarberov** [Refinitiv/Elektron-SDK#104]
cmake command:
 
"C:\ESDK13>cmake  -HC:\ESDK13 -BC:\ESDK13\build -G "Visual Studio 15 2017 Win64"
-DBUILD_EMA_UNIT_TESTS=OFF"

Error reported in CMakeError.Log:

CheckIncludeFile.c

C:\ESDK13\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\ESDK13\build\CMakeFiles\CMakeTmp\cmTC_f89ad.vcxproj]

[CMakeError.log](https://github.com/Refinitiv/Elektron-SDK/files/3118498/CMakeError.log)
[CMakeOutput.log](https://github.com/Refinitiv/Elektron-SDK/files/3118499/CMakeOutput.log)

**Comment by MitchellKato** [comment]
This is expected.  This is the method that CMake uses to detect if certain features are installed on the system, and will show this error in the output log if they're not present.  Since Windows doesn't have pthread.h, the header presence check will fail.

However, the generation should have succeeded, which can be checked through the output of either the CMake GUI or command line programs.

**Comment by zfarberov** [comment]
Thank you @MitchellKato 

Command line build output seems ok, no obvious errors.

However, neither ETA nor EMA folders in built CPP-C contain all of the same folders as a released 1.3 Cpp-C.    For example, there is no "Libs".

Should the resulting build contain everything, that a released Elektron-SDK-1.3.0.L1.win.rrg build contains?

**Comment by zfarberov** [comment]
Hello @MitchellKato ,

In README.MD I have followed and copied "-H":
"cmake -HElektron-SDK -Bbuild-esdk -G "VisualStudioVersion""

Opening Esdk.sln and building was the key step that I was missing.

Having done that I have been able to progress further and Libs folders were created and contain the libraries.

The run result was:
"========== Rebuild All: 168 succeeded, 86 failed, 1 skipped =========="

Does this look about right, or something did not build as expected?

[esk13build.20190429.txt](https://github.com/Refinitiv/Elektron-SDK/files/3128283/esk13build.20190429.txt)

Thanks!

**Comment by MitchellKato** [comment]
The errors appear to be caused by an incomplete VS2017 install.  VS2017 also requires the following optional install components for native C/C++ applications:
MFC and ATL support(x86 and x64)
C++/CLI support

Re-run the VS2017 installer, select "modify", and make sure that the above components are checked.

**Comment by zfarberov** [comment]
Thank you @MitchellKato 
This was it.
