### ISSUE TITLE
ETA Java:  incorrect dependency

### ISSUE THREAD

**Issue by addicticks-dev** [Refinitiv/Elektron-SDK#94]
The Maven POM for ETA Java pulls in Mockito as a normal dependency. This is incorrect. Mockito is only used for unit testing.

The problem is in [build.gradle](https://github.com/thomsonreuters/Elektron-SDK/blob/master/Java/Eta/Core/build.gradle): 

```groovy
dependencies {
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.1.2'
    compile group: 'org.apache.httpcomponents', name: 'httpmime', version: '4.1.2'
    compile group: 'org.apache.httpcomponents', name: 'httpclient-cache', version: '4.1.2'

    compile group: 'org.mockito', name: 'mockito-all', version: '1.9.0'   // ***

    testCompile group: 'org.mockito', name: 'mockito-all', version: '1.9.0'

    // needed for cobertura
    testRuntime group: 'org.slf4j', name: 'slf4j-api', version: '1.7.12'
}
```

Note that Mockito is referenced twice. The line I've marked with "***" should be deleted.

**Comment by brettjbush** [comment]
@addicticks-dev thank you, our team is assessing your report.

Currently, there are no gradle projects that depend on the testCompile group. Therefore, the testCompile group may be removed.

The Eta project depends on the compile group for both source code and unit testing for Eta:Core and Eta:ValueAdd. Mockito is therefore needed to compile the unit testing for the compile group.

In the future, we may separate the ETA unit testing in separate gradle projects so that Mockito can be defined in testCompile for testing purposes only.

**Comment by addicticks-dev** [comment]
Not familiar with Gradle but pretty sure the `compile` dependency in `build.gradle` on Mockito gets carried into Maven Central:

https://search.maven.org/artifact/com.thomsonreuters.upa/upa/3.2.2.0/jar
(look at the POM - pretty sure it is auto-generated by your builds? - it has Mockito as a normal dependency  ...Mockito shouldn't be there at all)

This explicit dependency on Mockito is unfortunate and unnecessary. It means that anyone who uses Eta via Maven Central will pull with him Mockito also even in production packages.

I'm assuming the POM which is used for Maven Central isn't hand-crafted? , i.e. I'm assuming it is derived from `build.gradle`. Therefore the culprit is `build.gradle`.

**Comment by vlevendel** [comment]
@addicticks-dev ESDK-1.3.1.L1 has a fix for this issue.  Please reopen if this is still an issue. Closing.
